version: '3.9'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'sassa'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: flashcard
    volumes:                # 3
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:

